Clean up partial download, Fix font deletion script

diff --git a/layout/usr/bin/efmrm b/layout/usr/bin/efmrm
--- a/layout/usr/bin/efmrm
+++ b/layout/usr/bin/efmrm
@@ -11,11 +11,18 @@ fi
 
 FONT_PATH="/Library/Themes/EmojiFontManager/$INSTALL_NAME.font"
 
+if [ ! -d "$FONT_PATH" ]; then
+    FONT_PATH="/var/jb/Library/Themes/EmojiFontManager/$INSTALL_NAME.font"
+fi
+
+if [ ! -d "$FONT_PATH" ] && command -v jbroot &> /dev/null; then
+    FONT_PATH="$(jbroot)Library/Themes/EmojiFontManager/$INSTALL_NAME.font"
+fi
+
 if [ -d "$FONT_PATH" ]; then
     rm -rf "$FONT_PATH"
+    echo "Font successfully removed."
 else
-    FONT_PATH="/var/jb/Library/Themes/EmojiFontManager/$INSTALL_NAME.font"
-    if [ -d "$FONT_PATH" ]; then
-        rm -rf "$FONT_PATH"
-    fi
+    echo "Error: Font '$INSTALL_NAME' is not installed."
+    exit 1
 fi
